# Arquitectura Solución - Workflow Configuration
name: "arquitectura-solucion"
description: "Workflow para generar documentación de arquitectura basada en arc42, incluyendo contexto, restricciones, estrategia de solución y vistas estáticas/dinámicas"
author: "Método Ceiba"
version: "1.0.0"

# Critical variables load from config_source
config_source: "{project-root}/.ceiba-metodo/metodo-ceiba/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Required inputs from user
required_inputs:
  - project_name: "Nombre del proyecto para el cual se genera la arquitectura"

# Optional docs that are loaded and analyzed during workflow execution
recommended_inputs:
  - prd: "Documento de requisitos del producto con FR y NFR"
  - epicas: "Épicas con historias de usuario y criterios de aceptación"
  - brief_alcance: "Resumen de necesidades y alcance del producto"
  - reporte_validacion_prd: "Reporte de validación de completitud del PRD (generado por workflow validar-completitud-prd)"

# Module path and component files
installed_path: "{project-root}/.ceiba-metodo/metodo-ceiba/workflows/arquitectura/crear-arquitectura-solucion"
template: true # This is a document workflow - generates template
instructions: "{installed_path}/instructions.md"
template_file: "{installed_path}/templates/solution-architecture-template.md"
validation: "{installed_path}/checklist.md"

# Output configuration
default_output_file: "{output_folder}/propuesta/04-arquitectura/arquitectura-solucion-comercial.md"
output_format: "markdown"

# Workflow settings
elicitation_mode: "advanced"

# Web bundle configuration for portability