# Revisar Historia v5
name: "revisar-historia"
description: "Revisión de código con TODOs por tipo+archivo para análisis enfocado"
version: "5.0.0"

standalone: true
config_source: "{project-root}/.ceiba-metodo/metodo-ceiba/config.yaml"

# Variables requeridas por instructions.xml
variables:
  communication_language: "{config_source}:communication_language"
  document_output_language: "{config_source}:document_output_language"
  dev_story_location: "{config_source}:dev_story_location"
  incident_location: "{config_source}:incident_location"

# Archivos del workflow
installed_path: "{project-root}/.ceiba-metodo/metodo-ceiba/workflows/desarrollo/revisar-historia"
instructions: "{installed_path}/instructions.xml"
