# Contexto Técnico - Sub-workflow Configuration
name: "contexto-tecnico"
description: "Carga contexto técnico del proyecto: análisis arquitectónico de la historia, GPS arquitectónico, estándares de código, documentación de componentes y flujos, y detección del tech stack"
author: "Método Ceiba - Peer Reviewer"
version: "1.0.0"

# Parent workflow
parent_workflow: "{project-root}/.ceiba-metodo/metodo-ceiba/workflows/desarrollo/revisar-historia/workflow.yaml"
standalone: false

# Critical variables inherited from parent
config_source: "{project-root}/.ceiba-metodo/metodo-ceiba/config.yaml"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
architecture_sharded_location: "{config_source}:architecture_sharded_location"
architecture_file: "{config_source}:architecture_file"

# Module path
installed_path: "{project-root}/.ceiba-metodo/metodo-ceiba/workflows/desarrollo/revisar-historia/sub-workflows/1-contexto-tecnico"
instructions: "{installed_path}/instructions.md"

# Variables received from parent
variables:
  story_context: "passed-from-parent" # {story_number, story_path, status, criterios_aceptacion[], tasks[], dev_agent_record}
  architecture_location: "passed-from-parent" # {architecture_sharded_location}

# Variables for architecture docs
arch_docs_file_names: ["index.md", "coding-standards.md", "architecture-*.md", "component-*.md", "flujo-*.md", "flow-*.md"]
coding_standards_file: "coding-standards.md"

# Output: Markdown directo al contexto del padre (no JSON intermedio)
output_format: "context_summary"
max_output_tokens: 500

# Execution hints
execution_hints:
  interactive: false
  autonomous: true
  validation_required: false

tags:
  - manual-review
  - context-loading
  - architecture
  - tech-stack
