# Estimar Historia de Usuario - Workflow Configuration
name: "estimar-historia-usuario"
description: "Estimar tiempos de desarrollo para historias de usuario previamente refinadas, calculando estimaciones para diferentes perfiles de desarrollador incluyendo el Método Ceiba"
author: "juan"

# Critical variables from config
config_source: "{project-root}/.ceiba-metodo/metodo-ceiba/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Module path and component files
installed_path: "{project-root}/.ceiba-metodo/metodo-ceiba/workflows/desarrollo/estimar-historia-usuario"
template: true
instructions: "{installed_path}/instructions.md"
template_file: "{installed_path}/template.md"
validation: "{installed_path}/checklist.md"

# Variables used in workflow - resolved from config_source or prompted
variables:
  story_number: "prompt" # Número de la historia a estimar
  dev_story_location: "{config_source}:dev_story_location" # Directory where stories are stored
  incident_location: "{config_source}:incident_location" # Directory where incidents are stored
  dod_pivots_location: "{config_source}:dod_pivots_location" # DoD pivots table (REQUIRED)
  architecture_sharded_location: "{config_source}:architecture_sharded_location" # Architecture docs location

# ============================================================================
# ARCHIVOS DE CONFIGURACIÓN REQUERIDOS (BLOQUEANTE)
# ============================================================================
required_project_files:
  - name: "dod-pivots.md"
    path: "{dod_pivots_location}"
    description: "Tabla de pivotes DoD y técnicos - Define tiempos para tareas manuales y técnicas"
    severity: "BLOCKING"
    generator_workflow: "*administrar-pivotes-dod"
    impact: "Sin este archivo, la estimación de tareas manuales usará valores genéricos poco precisos"
  - name: "coding-standards.md"
    path: "{architecture_sharded_location}/coding-standards.md"
    description: "Estándares de código del proyecto"
    severity: "WARNING"
    generator_workflow: "*generar-estandares-codigo"
    impact: "Recomendado para validar que las tareas sigan estándares del equipo"

# Output configuration - enriches existing story file
default_output_file: "{dev_story_location}/{story_number}.story.md"
output_mode: "enrich" # Enrich existing file with estimation section

# Estimation factors - configurable for calibration
estimation_factors:
  # Método Ceiba optimization (discount percentage)
  metodo_ceiba_discount: 0.60 # 60% de ahorro vs tradicional (te quedas con 40% del tiempo)

  # Role multipliers by complexity level (apply to both Traditional and Método Ceiba)
  multipliers:
    BAJA:
      junior: 1.5
      semi_senior: 1.2
    MEDIA:
      junior: 2.5
      semi_senior: 1.6
    ALTA:
      junior: 4.0
      semi_senior: 2.0
