# Validación de Testing - Sub-workflow Configuration
name: "validacion-testing"
description: "Consolida análisis de tests unitarios e integración"
author: "Método Ceiba - Peer Reviewer"
version: "2.0.0"

# Parent workflow
parent_workflow: "{project-root}/.ceiba-metodo/metodo-ceiba/workflows/desarrollo/revisar-historia/workflow.yaml"
standalone: false

# Critical variables inherited from parent
config_source: "{project-root}/.ceiba-metodo/metodo-ceiba/config.yaml"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"

# Module path
installed_path: "{project-root}/.ceiba-metodo/metodo-ceiba/workflows/desarrollo/revisar-historia/sub-workflows/4-validacion-testing"
instructions: "{installed_path}/instructions.md"

required_inputs:
  - staged_files
  - story_number
  - manual_context

outputs:
  - unitarios: Hallazgos tests unitarios
  - integracion: Hallazgos tests integración
  - coverage: Métricas de cobertura
  - findings: Lista consolidada de hallazgos

# Tasks XML con lógica de evaluación detallada
tasks:
  - id: diagnostic-unit-tests
    file: "{parent_path}/tasks/diagnostic-unit-tests.xml"
    description: Patrón AAA, mocks, test data builder
  - id: diagnostic-integration-tests
    file: "{parent_path}/tasks/diagnostic-integration-tests.xml"
    description: NO mocks internos, integración real
