# Análisis de Código - Sub-workflow Configuration
name: "analisis-codigo"
description: "Consolida diagnósticos de seguridad, backend y frontend"
author: "Método Ceiba - Peer Reviewer"
version: "2.0.0"

# Parent workflow
parent_workflow: "{project-root}/.ceiba-metodo/metodo-ceiba/workflows/desarrollo/revisar-historia/workflow.yaml"
standalone: false

# Critical variables inherited from parent
config_source: "{project-root}/.ceiba-metodo/metodo-ceiba/config.yaml"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"

# Module path
installed_path: "{project-root}/.ceiba-metodo/metodo-ceiba/workflows/desarrollo/revisar-historia/sub-workflows/3-analisis-codigo"
instructions: "{installed_path}/instructions.md"

required_inputs:
  - staged_files
  - story_number
  - manual_context

outputs:
  - seguridad: Hallazgos OWASP/BOLA
  - backend: Hallazgos arquitectura backend
  - frontend: Hallazgos frontend (o No Aplica)
  - findings: Lista consolidada de hallazgos

# Tasks XML con lógica de evaluación detallada
tasks:
  - id: diagnostic-seguridad
    file: "{parent_path}/tasks/diagnostic-seguridad.xml"
    description: Análisis BOLA y OWASP Top 10
  - id: diagnostic-backend
    file: "{parent_path}/tasks/diagnostic-backend.xml"
    description: Arquitectura, errores, mantenibilidad
  - id: diagnostic-frontend
    file: "{parent_path}/tasks/diagnostic-frontend.xml"
    description: Arquitectura frontend
    conditional: true
